#!/bin/bash

DIST=./dist

if [[ ! -d ${DIST} ]]; then
	echo 'ERROR: '${DIST}' directory not found. Abort'
	exit 1
fi

distpath=`readlink -f -- dist`

if [[ ! ${LD_LIBRARY_PATH} ]]; then
	export LD_LIBRARY_PATH=${distpath}
else
	export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}':'${distpath}
fi

echo 'Done'

